#!/bin/sh

# Convert man pages to html files.

for dir in man/prog man/libr man/func man/misc man/file; do
  for template in $dir/*.in;do
    page=`basename "$template" .in`
    if [ `wc -l < $template` -gt 1 ]; then
      html="html/$page.html"
      man2html -r $dir/$page | sed -s 's/\.\.\/man[0-9]*\///g' | sed -s 's/HREF="\.\.\//HREF="/g' | sed -s 's/\.[0-9][0-9]*\.html/.html/g' > $html
    fi
  done
done

# Convert the change log into a web page.

cd html
echo '<html><head><title>The tecla library change log</title></head>' > changes.html
echo '<body bgcolor="#add8e6"><pre>' >> changes.html
sed 's/&/&amp;/g; s/</\&lt;/g; s/>/\&gt;/g' ../CHANGES >> changes.html
echo '</pre></body></html>' >> changes.html

# Do the same to the release-notes file.

cd ../html
echo '<html><head><title>The tecla library release notes</title></head>' > release.html
echo '<body bgcolor="#add8e6"><pre>' >> release.html
sed 's/&/&amp;/g; s/</\&lt;/g' ../RELEASE.NOTES >> release.html
echo '</pre></body></html>' >> release.html
